import { Onest } from 'next/font/google'
import styles from "./layout.module.css"

import "./globals.css";
import Link from 'next/link';
import Header from './components/header/header';

/* 
const onest = Onest({
  subsets: ['latin']
})
 */


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body /* className={onest.classname} */>
       {/*  <Header/> */}
        {children}
      </body>
      
    </html>
    
  );
}
